// Auto-generated fixture rule-status data, built from the real per-rule verdicts
// produced while implementing each category page against the actual rule source
// in georank-ai/apps/backend. Do not hand-edit IDs -- regenerate from
// rule-inventory-for-fixture.txt if the inventory changes.

export type RuleStatus =
  | 'BROKEN'
  | 'NOT_APPLICABLE'
  | 'CANNOT_BREAK_ON_VERCEL'
  | 'CANNOT_BREAK_STATICALLY'
  | 'CANNOT_BREAK_IN_NEXTJS'
  | 'CANNOT_BREAK_WITHOUT_BLOCKING_CRAWL';

export interface RuleStatusEntry {
  id: string;
  scope: 'PAGE' | 'SITE';
  category: string;
  page: string;
  status: RuleStatus;
  how: string;
}

export const RULE_STATUS: RuleStatusEntry[] = [
  // ---- accessibility (14 PAGE) ----
  { id: 'accessibility.aria_attribute_validity', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'Invalid ARIA attribute name (aria-labl, typo of aria-label).' },
  { id: 'accessibility.aria_role_validity', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'Invalid role value (role="banner-thing").' },
  { id: 'accessibility.button_accessible_name', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'Icon-only <button> with no text/aria-label/title.' },
  { id: 'accessibility.color_contrast', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'NOT_APPLICABLE', how: 'Rule always returns NOT_APPLICABLE by design -- needs rendered/resolved CSS colors unavailable to a static crawler.' },
  { id: 'accessibility.duplicate_alt', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'Two distinct <img> share identical non-empty alt text.' },
  { id: 'accessibility.duplicate_id', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'dangerouslySetInnerHTML injects two elements with id="dup-section" (bypasses React dedup).' },
  { id: 'accessibility.empty_alt', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'Content <img alt=""> on a non-decorative photo.' },
  { id: 'accessibility.form_label_association', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: '<input> with no label / aria-label / aria-labelledby.' },
  { id: 'accessibility.image_alt', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: '<img> with alt attribute entirely absent.' },
  { id: 'accessibility.image_filename_quality', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'Filenames like IMG_4821.jpg, DSC00193.png match the generic-filename pattern.' },
  { id: 'accessibility.keyboard_navigation', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'No skip-nav link anywhere on the page; a clickable div has onClick with no tabIndex/keyboard handler.' },
  { id: 'accessibility.lang_attribute', scope: 'PAGE', category: 'accessibility', page: '/ (root layout, site-wide)', status: 'BROKEN', how: 'Root layout sets <html lang=""> (empty string). The crawler reads lang via $("html").attr("lang")?.trim() || null -- an empty string trims to falsy and becomes null, so every page on the site genuinely reports no lang attribute (WARNING), not just /accessibility.' },
  { id: 'accessibility.link_accessible_name', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: '<a> contains only a decorative aria-hidden svg, no text/aria-label/title.' },
  { id: 'accessibility.responsive_images', scope: 'PAGE', category: 'accessibility', page: '/accessibility', status: 'BROKEN', how: 'Large <img> with no srcset/sizes.' },

  // ---- ai_readability (10 PAGE) ----
  { id: 'ai_readability.content_chunk_size', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: 'Two giant merged-wall paragraphs (~1000 words each), 100% wall ratio vs 0.3 threshold.' },
  { id: 'ai_readability.definition_blocks', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'NOT_APPLICABLE', how: 'Opportunity-only rule; no heading matches the definition pattern, so it never fails on absence.' },
  { id: 'ai_readability.extractability', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: 'No short paragraphs, no lists, no tables, no FAQ/definition -- composite score ~20 vs warn 45.' },
  { id: 'ai_readability.heading_density', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: '2105 words over 3 headings, 702 words/heading exceeds the 700 hard-fail threshold.' },
  { id: 'ai_readability.heading_hierarchy', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: 'Heading order H1->H4->H6 skips two levels (>=2 skip threshold).' },
  { id: 'ai_readability.lists_usage', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: '2105 words, zero <ul>/<ol> anywhere on the page.' },
  { id: 'ai_readability.paragraph_length', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: 'Average paragraph ~1041 words, far past the 180-word hard-fail threshold.' },
  { id: 'ai_readability.reading_difficulty', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: 'Flesch Reading Ease score clamps to 0, well below the 30 warn threshold.' },
  { id: 'ai_readability.sentence_length', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: 'Constructed run-on sentences average ~190 words/sentence vs the 34-word run-on threshold.' },
  { id: 'ai_readability.whitespace_distribution', scope: 'PAGE', category: 'ai_readability', page: '/ai-readability', status: 'BROKEN', how: '5 content blocks over 2105 words, 421 words/block exceeds the 250 hard-fail threshold.' },

  // ---- ai_summarization (10 PAGE) ----
  { id: 'ai_summarization.actionable_information', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'How-to-styled H1 triggers how-to intent, but zero actionable steps/lists anywhere -- 0 signals.' },
  { id: 'ai_summarization.ai_citation_readiness', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'No factual/definition sentences, no lists/tables, no summary heading -- composite readiness near 0.' },
  { id: 'ai_summarization.content_compression_ratio', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'Long, hedging, repetitive filler paragraphs with low distinct-concept density.' },
  { id: 'ai_summarization.extractable_introduction', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'Opening paragraph starts with a context-dependent pronoun ("It also happened...") -- no intro framing match.' },
  { id: 'ai_summarization.key_takeaways', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'No Summary/Key Takeaways/TL;DR/Conclusion heading or label anywhere.' },
  { id: 'ai_summarization.logical_flow', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'Three unrelated H2 sections sharing no concepts, no opening frame, no closing summary.' },
  { id: 'ai_summarization.low_ambiguity', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'Heavy pronoun-led sentence openers push ambiguous-opener percentage well above threshold.' },
  { id: 'ai_summarization.standalone_paragraphs', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'Paragraphs open with context-dependent connectives (However, Furthermore, Consequently, ...).' },
  { id: 'ai_summarization.structured_information', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'Zero lists, tables, or TOC blocks on the page.' },
  { id: 'ai_summarization.summary_consistency', scope: 'PAGE', category: 'ai_summarization', page: '/ai-summarization', status: 'BROKEN', how: 'H1/title topic shares no concepts with section headings; body includes a self-contradicting claim.' },

  // ---- content (21 PAGE) ----
  { id: 'content.content_to_html_ratio', scope: 'PAGE', category: 'content', page: '/content', status: 'BROKEN', how: '10 levels of nested wrapper divs inflate markup vs body text, ratio well under 10%.' },
  { id: 'content.duplicate_paragraph', scope: 'PAGE', category: 'content', page: '/content', status: 'BROKEN', how: 'Same ~44-word paragraph repeated verbatim twice.' },
  { id: 'content.external_references', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Rule only applies at >=600 words; page is ~88 words, below the applicability floor.' },
  { id: 'content.faq_detection', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Rule can only PASS or NOT_APPLICABLE by design; no FAQ pattern present.' },
  { id: 'content.freshness', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Rule only applies when a publish/modified date is declared; page has none.' },
  { id: 'content.internal_references', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Requires >=400 words to apply; page is ~88 words.' },
  { id: 'content.lists_usage', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Requires >=500 words to apply; page is ~88 words.' },
  { id: 'content.media_usage', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Requires >=500 words to apply; page is ~88 words.' },
  { id: 'content.originality_signals', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Cross-page site-wide check requiring >=3 pages sharing a paragraph across >30% of them; single-page scope can’t drive it.' },
  { id: 'content.paragraph_length', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Paragraphs are short (~44 words) by design, under the 150-word cap, to keep thin_content/word_count triggering FAIL instead.' },
  { id: 'content.passive_voice', scope: 'PAGE', category: 'content', page: '/content', status: 'BROKEN', how: 'Heavy "is/are being + past participle" constructions push passive-sentence ratio above the 25% threshold.' },
  { id: 'content.readability', scope: 'PAGE', category: 'content', page: '/content', status: 'BROKEN', how: 'Long run-on sentences plus heavy passive voice contribute to composite readability issue count.' },
  { id: 'content.readability_score', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Requires >=150 words to apply; total content is ~88 words.' },
  { id: 'content.search_intent_match', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Rule is permanently disabled/stubbed in the codebase -- no target-keyword input exists.' },
  { id: 'content.semantic_keyword_coverage', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Permanently disabled/stubbed, same as search_intent_match.' },
  { id: 'content.sentence_length', scope: 'PAGE', category: 'content', page: '/content', status: 'BROKEN', how: 'Long multi-clause run-on sentences average well over the 25-word threshold.' },
  { id: 'content.table_usage', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Only triggers when title/headings mention pricing/comparison/specs; this page has no such signal.' },
  { id: 'content.thin_content', scope: 'PAGE', category: 'content', page: '/content', status: 'BROKEN', how: 'Total word count (~88) well under the 150/300-word thresholds.' },
  { id: 'content.toc_detection', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Requires >=1200 words to apply.' },
  { id: 'content.topic_completeness', scope: 'PAGE', category: 'content', page: '/content', status: 'NOT_APPLICABLE', how: 'Permanently disabled/stubbed, no content-brief input exists.' },
  { id: 'content.word_count_analysis', scope: 'PAGE', category: 'content', page: '/content', status: 'BROKEN', how: '~88 words for an "other" page type, under the 120-word minimum.' },

  // ---- conversational_structure (10 PAGE) ----
  { id: 'conversational_structure.question_headings', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'BROKEN', how: '3 H2 headings, none question-phrased, no leading interrogative or "?".' },
  { id: 'conversational_structure.answer_first', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'NOT_APPLICABLE', how: 'No question-posing headings/FAQ pattern present, so hasQuestions is false and the rule short-circuits.' },
  { id: 'conversational_structure.callout_blocks', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'BROKEN', how: 'Zero paragraphs/headings start with Tip:/Note:/Important: on a >500-word page.' },
  { id: 'conversational_structure.comparison_sections', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'NOT_APPLICABLE', how: 'No vs/versus/pros-cons/alternatives wording or tables, so signals === 0 and the rule has nothing to flag.' },
  { id: 'conversational_structure.dialogue_readability', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'BROKEN', how: 'Zero "?" marks, zero second-person pronouns, zero instructional verbs in body text.' },
  { id: 'conversational_structure.how_to_structure', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'NOT_APPLICABLE', how: 'No step/"how to"/"first,"/"step 1" wording anywhere.' },
  { id: 'conversational_structure.natural_language_flow', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'BROKEN', how: 'Heavy repetition of "platform" (~90+ occurrences) exceeds the keyword-share fail threshold.' },
  { id: 'conversational_structure.question_coverage', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'BROKEN', how: 'Zero of the 8 WH-word interrogatives (what/why/how/when/where/who/can/should) appear anywhere.' },
  { id: 'conversational_structure.answer_completeness', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'NOT_APPLICABLE', how: 'Same hasQuestions gate as answer_first, false.' },
  { id: 'conversational_structure.topic_transition', scope: 'PAGE', category: 'conversational_structure', page: '/conversational-structure', status: 'BROKEN', how: 'Duplicate H2 label ("Platform Overview" used twice) plus one empty H2 label exceed maxDupRatio.' },

  // ---- eeat (3 PAGE, 5 SITE) ----
  { id: 'eeat.author_bio', scope: 'PAGE', category: 'eeat', page: '/blog/eeat', status: 'NOT_APPLICABLE', how: 'Rule only fires when authorName is present; with no author declared there is no bio concept to check (author_information already fails for the missing author).' },
  { id: 'eeat.author_information', scope: 'PAGE', category: 'eeat', page: '/blog/eeat', status: 'BROKEN', how: 'No author byline text, no meta[name=author], no JSON-LD author, on a page classified pageType=blog (path under /blog/).' },
  { id: 'eeat.author_schema', scope: 'PAGE', category: 'eeat', page: '/blog/eeat', status: 'BROKEN', how: 'No JSON-LD on the page at all, so hasAuthorSchema is false, on a /blog/ page.' },
  { id: 'eeat.about_page', scope: 'SITE', category: 'eeat', page: 'site-wide', status: 'BROKEN', how: 'No /about page exists anywhere on the site and nothing links to one.' },
  { id: 'eeat.business_trust_signals', scope: 'SITE', category: 'eeat', page: 'site-wide', status: 'BROKEN', how: 'No <address> element, mailto: link, or tel: link anywhere in the site.' },
  { id: 'eeat.contact_information', scope: 'SITE', category: 'eeat', page: 'site-wide', status: 'BROKEN', how: 'No /contact page and no mailto:/tel: links anywhere.' },
  { id: 'eeat.privacy_policy', scope: 'SITE', category: 'eeat', page: 'site-wide', status: 'BROKEN', how: 'No privacy policy page exists or is linked.' },
  { id: 'eeat.terms_conditions', scope: 'SITE', category: 'eeat', page: 'site-wide', status: 'BROKEN', how: 'No terms & conditions page exists or is linked.' },

  // ---- eeat_signals (10 PAGE) ----
  { id: 'eeat_signals.author_expertise', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'NOT_APPLICABLE', how: 'Rule requires an author to be identified first; with none, authorIdentified is false.' },
  { id: 'eeat_signals.author_information', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'Zero author signals (name/schema/bio/profile link/image) on a page with substantial informational content.' },
  { id: 'eeat_signals.author_schema', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'No Person/Organization JSON-LD and no publisher reference for a page reading as informational content.' },
  { id: 'eeat_signals.content_accuracy_signals', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'Zero fact/statistic wording and zero verification links across >250 words.' },
  { id: 'eeat_signals.content_freshness', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'No publishedTime/modifiedTime meta and no freshness wording anywhere in text.' },
  { id: 'eeat_signals.content_ownership', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'No Organization/publisher JSON-LD, no copyright text, no consistent brand mention in body.' },
  { id: 'eeat_signals.organization_trust', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'No internal links to About/Contact/Privacy/Terms/Support and no mailto/tel/address elements.' },
  { id: 'eeat_signals.reputation_signals', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'Zero reputation wording (testimonial, trusted by, awards, ratings) and no Review/AggregateRating schema.' },
  { id: 'eeat_signals.source_citations', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'Zero external links to trusted hosts despite word count exceeding the 250-word applicability minimum.' },
  { id: 'eeat_signals.trust_indicators', scope: 'PAGE', category: 'eeat_signals', page: '/eeat-signals', status: 'BROKEN', how: 'No Privacy/Terms/Cookie trust links, no company contact details, no security/transparency wording.' },

  // ---- entity_richness (10 PAGE) ----
  { id: 'entity_richness.entity_consistency', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'NOT_APPLICABLE', how: 'No structured entity claims exist to corroborate (claims.length below the checkable minimum).' },
  { id: 'entity_richness.entity_density', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'BROKEN', how: 'Near-zero entity mentions (no proper nouns, no JSON-LD) against 463 words -- per-100 far below the low threshold.' },
  { id: 'entity_richness.entity_diversity', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'BROKEN', how: 'Zero distinct entity types detected, below the minimum of 2.' },
  { id: 'entity_richness.entity_relationships', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'BROKEN', how: 'Zero structured relations and fewer than 3 co-occurring visible entity types.' },
  { id: 'entity_richness.knowledge_graph_readiness', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'BROKEN', how: 'All four readiness pillars (structured data, relations, identity, context) score near zero.' },
  { id: 'entity_richness.named_entity_detection', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'BROKEN', how: 'Distinct entity count far below the minimum of 5 -- no schema nodes, no proper-noun phrases.' },
  { id: 'entity_richness.organization_identity', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'BROKEN', how: '0/5 identity signals: no Organization schema, name, logo/url, social links, or contact/address.' },
  { id: 'entity_richness.person_identity', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'NOT_APPLICABLE', how: 'Page is not an authored type and carries zero author signals, so hasAnyAuthorSignal is false.' },
  { id: 'entity_richness.product_service_entities', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'NOT_APPLICABLE', how: 'No Product/Service schema and pageType is neither product nor landing for this route.' },
  { id: 'entity_richness.schema_entity_coverage', scope: 'PAGE', category: 'entity_richness', page: '/entity-richness', status: 'BROKEN', how: 'Zero relevant schema @types present (typeCount === 0) -- hard FAIL.' },

  // ---- faq_optimization (10 PAGE) ----
  { id: 'faq_optimization.section_exists', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'No schema, no FAQ heading, fewer than 2 question headings -- hasAnyFaqSignal is false, and the rule design treats "no FAQ intent" as NOT_APPLICABLE rather than FAIL.' },
  { id: 'faq_optimization.count', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'Same hasAnyFaqSignal gate as section_exists.' },
  { id: 'faq_optimization.schema', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'No JSON-LD FAQPage block at all -- rule reports NOT_APPLICABLE rather than FAIL when no FAQ intent exists.' },
  { id: 'faq_optimization.answer_quality', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'schema.pairs.length === 0, no FAQPage answer text to measure.' },
  { id: 'faq_optimization.extractability', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'schema.pairs.length === 0.' },
  { id: 'faq_optimization.freshness', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'hasAnyFaqSignal is false.' },
  { id: 'faq_optimization.internal_linking', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'hasAnyFaqSignal is false.' },
  { id: 'faq_optimization.placement', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'No FAQ heading indices or schema pairs to place.' },
  { id: 'faq_optimization.question_diversity', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'hasAnyFaqSignal is false.' },
  { id: 'faq_optimization.question_quality', scope: 'PAGE', category: 'faq_optimization', page: '/faq-optimization', status: 'NOT_APPLICABLE', how: 'hasAnyFaqSignal is false. Note: all 10 rules in this category are deliberately calibrated to gate on FAQ intent existing at all (see faq-section-exists.rule.ts comments) -- a page with zero FAQ content structurally reports NOT_APPLICABLE, never FAIL, by the real rule design.' },

  // ---- internal_linking (12 PAGE, 8 SITE) ----
  { id: 'internal_linking.anchor_text_quality', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: 'Generic ("click here"/"read more"/"here") and repeated anchor text across links.' },
  { id: 'internal_linking.broken_links', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: 'Link to /internal-linking/this-page-does-not-exist-xyz, a real non-existent route.' },
  { id: 'internal_linking.crawl_depth', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: 'Nested unlinked path /internal-linking/same-target/canonical-variant with no shallow inbound links.' },
  { id: 'internal_linking.generic_anchor_text', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: '"click here"/"read more"/"here" anchors match the rule’s generic-phrase set.' },
  { id: 'internal_linking.internal_link_followability', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: 'href="#" with rel="nofollow" placeholder anchor pointing at the page’s own URL.' },
  { id: 'internal_linking.javascript_internal_links', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'NOT_APPLICABLE', how: 'Rule only detects href="javascript:..." pseudo-protocol hrefs; a plain onClick span with no href produces no link record for it to flag.' },
  { id: 'internal_linking.link_canonical_consistency', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking/same-target', status: 'BROKEN', how: 'Page declares canonical /internal-linking/same-target/canonical-variant while links target /internal-linking/same-target directly.' },
  { id: 'internal_linking.link_count', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: 'Only 2 distinct real internal link destinations, under the minimum threshold.' },
  { id: 'internal_linking.link_diversity', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: 'Nearly all 5 <a> links point at a single destination -- low distinct/total ratio.' },
  { id: 'internal_linking.links_present', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'NOT_APPLICABLE', how: 'Rule only fails at exactly zero internal links; page has 5 (needed for link_diversity to apply), so this rule PASSes while link_count covers the "too few but nonzero" case.' },
  { id: 'internal_linking.nofollow_internal_links', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: 'rel="nofollow" on all 5 real internal links (100% ratio vs the 60% FAIL threshold).' },
  { id: 'internal_linking.redirecting_links', scope: 'PAGE', category: 'internal_linking', page: '/internal-linking', status: 'BROKEN', how: 'Link to /internal-linking/old-redirecting-target, which server-redirects to /internal-linking/same-target.' },
  { id: 'internal_linking.hub_page_detection', scope: 'SITE', category: 'internal_linking', page: '/hub', status: 'BROKEN', how: '/hub receives 5 inbound links (meeting the hub threshold) but only links out to 1 page, below the outbound minimum.' },
  { id: 'internal_linking.important_page_inlinks', scope: 'SITE', category: 'internal_linking', page: '/pricing', status: 'BROKEN', how: '/pricing matches the key-page pattern and is crawled (via a buried 3-click path) with exactly 1 inbound link, below the 2-link minimum.' },
  { id: 'internal_linking.important_pages_reachability', scope: 'SITE', category: 'internal_linking', page: '/pricing', status: 'BROKEN', how: '/pricing is reachable only 3 clicks deep (home -> /blog/page/1 -> /blog/page/1/deeper -> /pricing), past the 2-click maximum.' },
  { id: 'internal_linking.inbound_links', scope: 'SITE', category: 'internal_linking', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Structurally unachievable: this coarse rule only FAILs when literally zero internal links exist anywhere in the whole crawl -- incompatible with having any navigable site at all. Its own source comments confirm every discovered page was, by construction, "linked from somewhere in this crawl" since the crawler only finds pages by following real <a href> links.' },
  { id: 'internal_linking.link_depth_distribution', scope: 'SITE', category: 'internal_linking', page: 'site-wide', status: 'BROKEN', how: '/pricing is reachable only via a 3-click-deep path (home -> /blog/page/1 -> /blog/page/1/deeper -> /pricing), pulling the site-wide depth distribution outside the healthy range for a site this small.' },
  { id: 'internal_linking.link_equity_distribution', scope: 'SITE', category: 'internal_linking', page: '/blog', status: 'BROKEN', how: '/blog links to /product three times and /hub once while /pricing gets only 1 inbound link overall, producing a high Gini coefficient.' },
  { id: 'internal_linking.link_to_5xx_ratio', scope: 'SITE', category: 'internal_linking', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Requires a same-site link that returns a real 5xx server error; Vercel/Next.js only ever serve a valid 200 or a clean 404 for unknown paths in production hosting.' },
  { id: 'internal_linking.orphan_pages', scope: 'SITE', category: 'internal_linking', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Structurally unachievable: the crawler discovers every page purely by following real <a href> links in a same-origin BFS from the homepage, with no sitemap-based discovery path feeding this particular rule beyond what BFS already found. A page with truly zero inbound links from anywhere is, by construction, never discovered/crawled at all, so it can never appear in ctx.allPages to be scored as an orphan.' },

  // ---- mobile (10 PAGE) ----
  { id: 'mobile.viewport_configured', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'BROKEN', how: 'Page-level viewport export {width:980, maximumScale:1, userScalable:false} matches both the fixed-width and zoom-lock patterns.' },
  { id: 'mobile.viewport_meta', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'CANNOT_BREAK_IN_NEXTJS', how: 'Next.js always injects a <meta name="viewport"> tag as a framework default field; a page-level viewport export only overwrites its content, never removes the tag.' },
  { id: 'mobile.mobile_content_width', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'BROKEN', how: 'A <div style="width:900px"> exceeds the 400px content-width proxy threshold.' },
  { id: 'mobile.mobile_image_scaling', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'BROKEN', how: '<img width=900 style="width:900px"> with no srcset/sizes.' },
  { id: 'mobile.mobile_navigation_crawlability', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'BROKEN', how: 'Nav links use href="#" / javascript:void(0) at a 1.0 ratio, over the 0.5 fail threshold.' },
  { id: 'mobile.mobile_table_handling', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'BROKEN', how: 'A <table style="width:960px"> exceeds the 400px threshold.' },
  { id: 'mobile.responsive_layout', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'BROKEN', how: 'Page’s viewport export has no device-width, so hasDeviceWidthViewport is false.' },
  { id: 'mobile.touch_target_size', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'NOT_APPLICABLE', how: 'Rule always returns NOT_APPLICABLE by design -- needs rendered layout geometry unavailable to a static crawler.' },
  { id: 'mobile.font_readability', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'NOT_APPLICABLE', how: 'Rule always returns NOT_APPLICABLE by design -- needs computed CSS.' },
  { id: 'mobile.horizontal_overflow', scope: 'PAGE', category: 'mobile', page: '/mobile', status: 'NOT_APPLICABLE', how: 'Rule always returns NOT_APPLICABLE by design -- needs rendered layout.' },

  // ---- on_page (26 PAGE, 1 SITE) ----
  { id: 'on_page.duplicate_h1', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Mutually exclusive with h1_present FAIL: rule requires an H1 to be present at all; page has zero.' },
  { id: 'on_page.duplicate_meta_description', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'Raw <meta name="description"> in body duplicates the root layout’s inherited description text.' },
  { id: 'on_page.duplicate_title', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Rule needs a non-empty canonical title; primary title is whitespace-only so empty_title/title_present take precedence.' },
  { id: 'on_page.empty_meta_description', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'metadata.description set to an empty string.' },
  { id: 'on_page.empty_title', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'metadata.title set to whitespace-only ("   ").' },
  { id: 'on_page.first_paragraph_content', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'First paragraph shares no topical token with the empty title / absent H1.' },
  { id: 'on_page.h1_length', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'No H1 exists; rule requires one to be present to measure length.' },
  { id: 'on_page.h1_present', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'Zero <h1> elements on the page.' },
  { id: 'on_page.heading_hierarchy', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'First heading on the page is an H2, not an H1.' },
  { id: 'on_page.heading_structure', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Page is under the 500-word applicability threshold.' },
  { id: 'on_page.main_content_presence', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'No <main>, [role=main], or <article> landmark -- plain wrapper div only.' },
  { id: 'on_page.meta_description', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'Meta description is empty.' },
  { id: 'on_page.meta_description_cta', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Page type is not landing/product, and description is empty anyway.' },
  { id: 'on_page.meta_description_length', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Rule requires a non-empty description to measure length.' },
  { id: 'on_page.missing_h2', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'One H2 exists (needed so heading_hierarchy can report its WARNING path) -- mutually exclusive tradeoff documented in the page.' },
  { id: 'on_page.multiple_meta_descriptions', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'Two meta-description tags: the metadata export ("") plus a raw <meta> tag in body.' },
  { id: 'on_page.multiple_title_tags', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'Two <title> tags: the metadata export plus a raw <title> in body.' },
  { id: 'on_page.open_graph_metadata', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'Only og:title is set; og:description and og:image are missing.' },
  { id: 'on_page.skipped_heading_levels', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'Heading order jumps H2 -> H4, skipping H3.' },
  { id: 'on_page.title_length', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Rule requires a non-empty title to measure length.' },
  { id: 'on_page.title_present', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'Whitespace-only title is normalized to empty by the crawler.' },
  { id: 'on_page.twitter_card_metadata', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'BROKEN', how: 'No Twitter Card metadata exported at all (twitter:card missing).' },
  { id: 'on_page.url_hyphen_usage', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Route path is fixed by the fixture spec and already hyphenated.' },
  { id: 'on_page.url_length', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Route path is fixed by the fixture spec and well under the length threshold.' },
  { id: 'on_page.url_lowercase', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Route path is fixed by the fixture spec and already lowercase. A dedicated dirty-URL demonstration exists separately at /technical-markup for url_structure.' },
  { id: 'on_page.url_readability', scope: 'PAGE', category: 'on_page', page: '/on-page', status: 'NOT_APPLICABLE', how: 'Route path is fixed by the fixture spec and already readable words.' },
  { id: 'on_page.title_brand_consistency', scope: 'SITE', category: 'on_page', page: '/', status: 'BROKEN', how: 'Every other page uses a "Page | Broken Fixture Co" title suffix convention; the homepage title is just "Welcome", breaking the detected site-wide convention.' },

  // ---- performance (17 PAGE) ----
  { id: 'performance.browser_caching', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Reads the HTTP response cache-control/expires headers, not page markup -- see technical.cache_headers for the header-level equivalent broken at /technical-headers/no-cache.' },
  { id: 'performance.cls', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Graded from real PageSpeed Insights lab data; rule returns NOT_APPLICABLE without a PSI measurement.' },
  { id: 'performance.compression', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Reads the HTTP response content-encoding header, not markup.' },
  { id: 'performance.fcp', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Graded from PSI lab data.' },
  { id: 'performance.font_optimization', scope: 'PAGE', category: 'performance', page: '/performance', status: 'BROKEN', how: '6 distinct <link rel=stylesheet> font resources with zero preload, exceeding the 4-resource threshold.' },
  { id: 'performance.image_bloat', scope: 'PAGE', category: 'performance', page: '/performance', status: 'BROKEN', how: '8 <img> tags, several with empty/missing alt.' },
  { id: 'performance.image_optimization', scope: 'PAGE', category: 'performance', page: '/performance', status: 'BROKEN', how: '8 plain <img> tags using legacy formats (.jpg/.png/.gif/.bmp) with no srcset.' },
  { id: 'performance.inp', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Rule always returns NOT_APPLICABLE; no interaction timeline from a static crawl.' },
  { id: 'performance.lcp', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Graded from PSI lab data.' },
  { id: 'performance.link_bloat', scope: 'PAGE', category: 'performance', page: '/performance', status: 'BROKEN', how: '110 generated <a> links in a nav list, exceeding the 100-link threshold.' },
  { id: 'performance.render_blocking_css', scope: 'PAGE', category: 'performance', page: '/performance', status: 'BROKEN', how: '3 <link rel=stylesheet> tags with no/all/screen media, exceeding the 2-stylesheet FAIL threshold.' },
  { id: 'performance.render_blocking_js', scope: 'PAGE', category: 'performance', page: '/performance', status: 'BROKEN', how: 'A synchronous external script plus an inline blocking script (large data blob + busy-loop), neither async/defer/module.' },
  { id: 'performance.speed_index', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Graded from PSI lab data.' },
  { id: 'performance.third_party_impact', scope: 'PAGE', category: 'performance', page: '/performance', status: 'BROKEN', how: '8 distinct third-party script origins, exceeding the 6-origin threshold.' },
  { id: 'performance.ttfb', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Reads crawler wall-clock response time, not markup -- see technical.server_response_time for the equivalent broken at /technical-headers/slow.' },
  { id: 'performance.unused_css', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Rule always returns NOT_APPLICABLE; needs CSSOM coverage data.' },
  { id: 'performance.unused_js', scope: 'PAGE', category: 'performance', page: '/performance', status: 'NOT_APPLICABLE', how: 'Rule always returns NOT_APPLICABLE; needs code-execution coverage data.' },

  // ---- security (5 PAGE) ----
  { id: 'security.headers_full', scope: 'PAGE', category: 'security', page: 'site-wide', status: 'BROKEN', how: 'next.config.ts sends no headers config at all -- CSP/X-Frame-Options/Referrer-Policy/Permissions-Policy/X-Content-Type-Options are all absent.' },
  { id: 'security.response_headers', scope: 'PAGE', category: 'security', page: 'site-wide', status: 'BROKEN', how: 'X-Content-Type-Options and X-Frame-Options both absent site-wide.' },
  { id: 'security.hsts_header', scope: 'PAGE', category: 'security', page: 'site-wide', status: 'BROKEN', how: 'Strict-Transport-Security is never sent.' },
  { id: 'security.hsts_preload_readiness', scope: 'PAGE', category: 'security', page: 'site-wide', status: 'BROKEN', how: 'HSTS header absent, so preload readiness cannot be satisfied either.' },
  { id: 'security.secure_cookies', scope: 'PAGE', category: 'security', page: '/security', status: 'BROKEN', how: 'middleware.ts sets a Set-Cookie for /security missing both Secure and HttpOnly.' },

  // ---- semantic_depth (10 PAGE) ----
  { id: 'semantic_depth.content_redundancy', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: 'One word ("storage") is repeated so heavily it far exceeds the 10% max-top-share threshold.' },
  { id: 'semantic_depth.definitions', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: '256 words clears the applicability floor but contains zero definition-pattern matches.' },
  { id: 'semantic_depth.examples', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: 'No example headings/phrases and no tables/media -- zero example signals.' },
  { id: 'semantic_depth.related_concepts', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: 'Distinct concept vocabulary is deliberately narrow, well under the minimum-distinct-concepts threshold.' },
  { id: 'semantic_depth.search_intent_coverage', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: 'No informational/commercial/transactional/navigational cue phrases present at all.' },
  { id: 'semantic_depth.semantic_relationships', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: 'No connective language (because/therefore/etc.) and trivial concept threading across paragraphs.' },
  { id: 'semantic_depth.supporting_evidence', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: 'Zero evidence phrases (no stats, "according to", citations) and zero authoritative external links.' },
  { id: 'semantic_depth.topic_completeness', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: 'No opening/definition heading and no closing/summary heading -- content arc mostly absent.' },
  { id: 'semantic_depth.topic_coverage', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: '3 H2 sections each with only 1-2 short sentences -- low words-per-section coverage.' },
  { id: 'semantic_depth.topical_authority', scope: 'PAGE', category: 'semantic_depth', page: '/semantic-depth', status: 'BROKEN', how: 'Composite of coverage/depth/evidence/references pillars all score near zero.' },

  // ---- structured_data (16 PAGE, 1 SITE) ----
  { id: 'structured_data.jsonld_exists', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'BROKEN', how: 'Zero JSON-LD blocks anywhere on the page.' },
  { id: 'structured_data.schema_present', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'BROKEN', how: 'page.hasSchema is false.' },
  { id: 'structured_data.webpage_schema', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'BROKEN', how: 'pageType "other" makes the rule applicable; no WebPage/subtype schema present.' },
  { id: 'structured_data.faqpage_schema', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'BROKEN', how: '5 question-phrased H2 headings trigger hasFaqPattern, making the rule applicable, but no FAQPage schema exists.' },
  { id: 'structured_data.rich_results_eligibility', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'BROKEN', how: 'FAQ intent is present via headings but no structured data qualifies for any rich result.' },
  { id: 'structured_data.article_schema', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'pageType is not blog.' },
  { id: 'structured_data.breadcrumblist_schema', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'pageType is neither blog nor product.' },
  { id: 'structured_data.duplicate_structured_data', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'jsonLdBlocks.length === 0, nothing to compare for duplicates.' },
  { id: 'structured_data.jsonld_valid_syntax', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'jsonLdBlocks.length === 0, nothing to parse.' },
  { id: 'structured_data.organization_schema', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'Rule only applies on the homepage; this is not the homepage.' },
  { id: 'structured_data.person_author_schema', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'pageType is not blog.' },
  { id: 'structured_data.product_schema', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'pageType is not product.' },
  { id: 'structured_data.required_properties', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'No typed JSON-LD nodes exist to check required properties on.' },
  { id: 'structured_data.schema_type_relevance', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'pageType "other" has no expected-type entry in the rule’s lookup table.' },
  { id: 'structured_data.valid_vocabulary', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'No typed nodes exist to validate vocabulary on.' },
  { id: 'structured_data.website_schema', scope: 'PAGE', category: 'structured_data', page: '/structured-data', status: 'NOT_APPLICABLE', how: 'Rule only applies on the homepage; this is not the homepage.' },
  { id: 'structured_data.coverage', scope: 'SITE', category: 'structured_data', page: 'site-wide', status: 'BROKEN', how: 'No JSON-LD structured data exists on any page in the site -- 0% coverage.' },

  // ---- technical (26 PAGE, 14 SITE) ----
  { id: 'technical.base_tag', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: '<base href="/technical-markup/"> is present (rule is presence-only, WARNING is the max achievable severity).' },
  { id: 'technical.broken_internal_links', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'Link to /technical-markup/this-route-does-not-exist-404.' },
  { id: 'technical.cache_headers', scope: 'PAGE', category: 'technical', page: '/technical-headers/no-cache', status: 'BROKEN', how: 'Middleware deletes Cache-Control and Expires headers for this route.' },
  { id: 'technical.canonical_conflicts', scope: 'PAGE', category: 'technical', page: '/technical-markup, /technical-markup/canonical-conflict-b', status: 'BROKEN', how: 'Two pages with different titles share the same canonical target (/technical-markup/redirect-me).' },
  { id: 'technical.canonical_redirect_target', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'Canonical points to /technical-markup/redirect-me, which 302-redirects instead of resolving 200.' },
  { id: 'technical.canonical_self_reference', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'Canonical points elsewhere (/technical-markup/redirect-me) instead of the page’s own URL.' },
  { id: 'technical.canonical_tag', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'NOT_APPLICABLE', how: 'Canonical is present (required so the self-reference/redirect-target rules can be exercised) -- this presence-only rule PASSes as a result.' },
  { id: 'technical.charset', scope: 'PAGE', category: 'technical', page: 'n/a', status: 'CANNOT_BREAK_IN_NEXTJS', how: 'Next.js always injects its own <meta charSet="utf-8"> as the first element in <head> ("Default Field"); a later manually-added charset meta has no effect on the first-match cheerio selector the rule reads, and the rule only fails on a MISSING charset (never on a mismatch) or warns on a genuinely unrecognized charset name.' },
  { id: 'technical.compression', scope: 'PAGE', category: 'technical', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Vercel’s edge automatically gzip/brotli-compresses text responses; no app-level Next.js config can disable it.' },
  { id: 'technical.content_type', scope: 'PAGE', category: 'technical', page: '/technical-headers/no-charset-param', status: 'BROKEN', how: 'Route handler sends Content-Type: text/html with no charset parameter.' },
  { id: 'technical.doctype', scope: 'PAGE', category: 'technical', page: 'n/a', status: 'CANNOT_BREAK_IN_NEXTJS', how: 'Next.js/React always emits <!doctype html> as the literal first bytes; no App Router mechanism can omit or alter it.' },
  { id: 'technical.external_links_secure', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'An <a target="_blank"> external link has no rel attribute.' },
  { id: 'technical.http_status', scope: 'PAGE', category: 'technical', page: '/technical-headers/status-500', status: 'BROKEN', how: 'Route handler returns a real HTTP 500.' },
  { id: 'technical.indexability', scope: 'PAGE', category: 'technical', page: '/technical-headers/indexability-blocked', status: 'BROKEN', how: 'Meta robots noindex on a linked, reachable, non-disallowed page.' },
  { id: 'technical.meta_robots_validation', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'metadata.robots = "index, noindex" -- conflicting directives on the same page.' },
  { id: 'technical.mixed_content', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'Two plain-HTTP <img src="http://..."> images embedded on the HTTPS page.' },
  { id: 'technical.noindex', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'The conflicting robots string used for meta_robots_validation ("index, noindex") also contains "noindex", so isNoindex is true; scoped to this one page, overall site crawlability is unaffected.' },
  { id: 'technical.page_size', scope: 'PAGE', category: 'technical', page: '/technical-headers/huge', status: 'BROKEN', how: '~2.4M-character inline filler blob, past the 2,000,000-char FAIL threshold.' },
  { id: 'technical.redirect_chains', scope: 'PAGE', category: 'technical', page: '/old-page', status: 'BROKEN', how: '2-hop redirect chain: /old-page -> /redirect-hop-2 -> /entity-richness.' },
  { id: 'technical.redirect_loops', scope: 'PAGE', category: 'technical', page: '/technical-headers/loop-a', status: 'BROKEN', how: 'Genuine A->B->A redirect cycle (loop-a -> loop-b -> loop-a) in next.config.ts, isolated under /technical-headers.' },
  { id: 'technical.redirect_target_relevance', scope: 'PAGE', category: 'technical', page: '/old-page', status: 'BROKEN', how: 'The redirect chain lands on /entity-richness, sharing no topical relationship with the /old-page source.' },
  { id: 'technical.server_response_time', scope: 'PAGE', category: 'technical', page: '/technical-headers/slow', status: 'BROKEN', how: 'Route handler awaits an artificial ~3.5s delay, past the 3000ms critical threshold.' },
  { id: 'technical.soft_404', scope: 'PAGE', category: 'technical', page: '/technical-headers/soft-404', status: 'BROKEN', how: 'Returns HTTP 200 with title/H1 "Page Not Found" and under 80 words of body content.' },
  { id: 'technical.trailing_slash_consistency', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'Links to /technical-markup/redirect-me both with and without a trailing slash.' },
  { id: 'technical.url_structure', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'A self-link with underscore query params and 4 query parameters (utm_source, utm_medium, sort_by, ref_id).' },
  { id: 'technical.x_robots_tag', scope: 'PAGE', category: 'technical', page: '/technical-markup', status: 'BROKEN', how: 'Middleware sets X-Robots-Tag: noindex, nofollow on this linked page.' },
  { id: 'technical.broken_external_links', scope: 'SITE', category: 'technical', page: '/', status: 'BROKEN', how: 'Homepage links to a non-resolving external domain.' },
  { id: 'technical.faceted_navigation', scope: 'SITE', category: 'technical', page: 'n/a', status: 'NOT_APPLICABLE', how: 'Rule is WARNING-only and never fires without facet-like URLs (?color=, ?sort=, etc.); building a fake faceted-listing subsystem was judged out of proportion for a QA fixture.' },
  { id: 'technical.http2_support', scope: 'SITE', category: 'technical', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Vercel terminates TLS at its edge and negotiates HTTP/2 (or HTTP/3) via ALPN for every deployment.' },
  { id: 'technical.http_to_https_redirect', scope: 'SITE', category: 'technical', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Vercel automatically redirects all http:// requests to https:// at the platform/edge level.' },
  { id: 'technical.https', scope: 'SITE', category: 'technical', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Vercel serves every deployment over HTTPS by default with automatic certificate provisioning.' },
  { id: 'technical.pagination_discoverability', scope: 'SITE', category: 'technical', page: 'n/a', status: 'NOT_APPLICABLE', how: 'Rule is WARNING-only and never fires without a paginated URL series (?page=N); this fixture has no paginated content type.' },
  { id: 'technical.robots_important_pages_blocked', scope: 'SITE', category: 'technical', page: '/robots.txt', status: 'BROKEN', how: 'robots.txt has Disallow: /pricing, and /pricing matches the important-page pattern, while the rest of the site stays crawlable.' },
  { id: 'technical.robots_txt', scope: 'SITE', category: 'technical', page: '/robots.txt', status: 'NOT_APPLICABLE', how: 'Intentionally left passing -- robots.txt is present and does not block the whole site, per the fixture’s crawlability requirement.' },
  { id: 'technical.robots_txt_validity', scope: 'SITE', category: 'technical', page: '/robots.txt', status: 'BROKEN', how: 'robots.txt contains malformed lines (missing colons, unrecognized directive shapes) that don’t match any recognized directive prefix.' },
  { id: 'technical.sitemap', scope: 'SITE', category: 'technical', page: '/sitemap.xml', status: 'NOT_APPLICABLE', how: 'Intentionally left passing -- a sitemap file is present, as required by the fixture’s crawlability constraints; its content defects are covered by sitemap_valid/sitemap_urls_reachable.' },
  { id: 'technical.sitemap_urls_reachable', scope: 'SITE', category: 'technical', page: '/sitemap.xml', status: 'BROKEN', how: 'Sitemap lists a URL with no matching route, unreachable in the sampled check.' },
  { id: 'technical.sitemap_valid', scope: 'SITE', category: 'technical', page: '/sitemap.xml', status: 'BROKEN', how: 'Root element is <urlsetx> instead of the required <urlset>/<sitemapindex> -- malformed root.' },
  { id: 'technical.ssl_certificate', scope: 'SITE', category: 'technical', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Vercel auto-provisions and renews a trusted TLS certificate for every deployment domain.' },
  { id: 'technical.www_redirect', scope: 'SITE', category: 'technical', page: 'n/a', status: 'CANNOT_BREAK_ON_VERCEL', how: 'Whether www/non-www both resolve is controlled by Vercel’s domain/DNS configuration, not app code.' },
];
